#!/usr/bin/env node
"use strict";

/**
 * Release metadata helper for release.ps1.
 * gate-api/data/releases.json is the single source of truth; this keeps the
 * EXE header, site fallback copy, and status-page client version in sync.
 *
 *   node release-meta.js next [--bump patch|minor|major] [--version X.Y.Z]
 *   node release-meta.js stamp --version X.Y.Z
 *   node release-meta.js latest-sha
 *   node release-meta.js record --version X.Y.Z --title "..." --notes-file notes.txt
 *                               --exe path\Oxide.exe [--dumper path\OxideDumper.exe]
 */

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.resolve(__dirname, "..", "..");
const RELEASES = path.join(ROOT, "gate-api", "data", "releases.json");
const SITE_COPY = path.join(ROOT, "gate-site", "public", "releases.json");
const VERSION_H = path.join(ROOT, "External", "src", "version.h");
const OFFSETS_H = path.join(ROOT, "External", "src", "sdk", "offsets.h");
const CLIENT_VERSION_TXT = path.join(ROOT, "gate-api", "data", "client-version.txt");

function args() {
  const out = { _: [] };
  const argv = process.argv.slice(2);
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) {
      const key = a.slice(2);
      const next = argv[i + 1];
      if (next === undefined || next.startsWith("--")) out[key] = true;
      else {
        out[key] = next;
        i++;
      }
    } else out._.push(a);
  }
  return out;
}

function readReleases() {
  if (!fs.existsSync(RELEASES)) return { product: "Oxide", releases: [] };
  const data = JSON.parse(fs.readFileSync(RELEASES, "utf8"));
  if (!Array.isArray(data.releases)) data.releases = [];
  return data;
}

function parseSemver(v) {
  const m = /^(\d+)\.(\d+)\.(\d+)$/.exec(String(v || "").trim().replace(/^v/i, ""));
  return m ? m.slice(1).map(Number) : null;
}

function nextVersion(opts) {
  if (opts.version && opts.version !== true) {
    const v = String(opts.version).replace(/^v/i, "");
    if (!parseSemver(v)) throw new Error(`Invalid version "${opts.version}" (expected X.Y.Z)`);
    if (readReleases().releases.some((r) => r.version === v)) {
      throw new Error(`Version ${v} already exists in releases.json`);
    }
    return v;
  }
  const latest = readReleases().releases[0];
  const cur = parseSemver(latest?.version) || [0, 0, 0];
  const bump = String(opts.bump || "patch");
  if (bump === "major") return `${cur[0] + 1}.0.0`;
  if (bump === "minor") return `${cur[0]}.${cur[1] + 1}.0`;
  return `${cur[0]}.${cur[1]}.${cur[2] + 1}`;
}

function stamp(version) {
  const body =
    "#pragma once\n" +
    "// Generated by release.ps1 from gate-api/data/releases.json — do not edit by hand.\n" +
    `#define OXIDE_VERSION "${version}"\n`;
  fs.writeFileSync(VERSION_H, body, "utf8");
}

function fileInfo(file) {
  const buf = fs.readFileSync(file);
  return {
    sha256: crypto.createHash("sha256").update(buf).digest("hex"),
    sizeBytes: buf.length,
  };
}

function readClientVersion() {
  try {
    const m = fs.readFileSync(OFFSETS_H, "utf8").match(/ClientVersion\s*=\s*"([^"]+)"/);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}

function writeJson(file, data) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(data, null, 2) + "\n", "utf8");
}

function record(opts) {
  const version = String(opts.version).replace(/^v/i, "");
  if (!parseSemver(version)) throw new Error("record: --version X.Y.Z required");
  const notes = fs
    .readFileSync(String(opts["notes-file"]), "utf8")
    .split(/\r?\n/)
    .map((l) => l.replace(/^\s*[-*•]\s*/, "").trim())
    .filter(Boolean);
  if (!notes.length) throw new Error("record: notes file is empty");

  const data = readReleases();
  if (data.releases.some((r) => r.version === version)) {
    throw new Error(`Version ${version} already exists in releases.json`);
  }

  const files = { "Oxide.exe": fileInfo(String(opts.exe)) };
  if (opts.dumper && opts.dumper !== true && fs.existsSync(String(opts.dumper))) {
    files["OxideDumper.exe"] = fileInfo(String(opts.dumper));
  }
  const clientVersion = readClientVersion();

  const entry = {
    version,
    title: opts.title && opts.title !== true ? String(opts.title) : null,
    date: new Date().toISOString(),
    clientVersion,
    changes: notes,
    files,
  };
  data.product = data.product || "Oxide";
  data.releases.unshift(entry);
  writeJson(RELEASES, data);
  writeJson(SITE_COPY, data);
  if (clientVersion) fs.writeFileSync(CLIENT_VERSION_TXT, `${clientVersion}\n`, "utf8");
  process.stdout.write(JSON.stringify(entry));
}

function main() {
  const opts = args();
  const cmd = opts._[0];
  if (cmd === "next") return process.stdout.write(nextVersion(opts));
  if (cmd === "stamp") return stamp(String(opts.version));
  if (cmd === "latest-sha") {
    return process.stdout.write(readReleases().releases[0]?.files?.["Oxide.exe"]?.sha256 || "");
  }
  if (cmd === "record") return record(opts);
  throw new Error(`Unknown command "${cmd || ""}"`);
}

try {
  main();
} catch (err) {
  process.stderr.write(`release-meta: ${err.message}\n`);
  process.exit(1);
}
